### ISSUE TITLE
Ocarina state inconsistent when reloading saved tracking info

### ISSUE THREAD

**Issue by KPJoshi** [Hamsda/EmoTrackerPacks#117]
When I load the attached JSON in EmoTracker, the ocarina shown is the Ocarina of Time. However, I have only acquired Saria's Ocarina so far. If I change it back to Saria's Ocarina, some of the squares on the map change color, I assume those require the OoT. More importantly, if I save the JSON after making the correction and reload it, the OoT shows up again instead of Saria's.

[ootr.zip](https://github.com/Hamsda/EmoTrackerPacks/files/6534268/ootr.zip)

**Comment by Hamsda** [comment]
Known issue and currently not really anything I can do on my side, waiting for a change in EmoTracker itself to fix this.

Basically it loads the item states from the save and then "marks off" all the locations that were marked off. So it kinda recollects the non shuffled ocarina at the KF bridge because of some lua shenanigans.

**Comment by KPJoshi** [comment]
I see. Do you want me to keep this issue open then? Also, I have not experienced such issues with the official LTTP randomizer tracker. But I don't know how different yours is from that one.

**Comment by Hamsda** [comment]
Yeah, its fine to stay open as a reminder.
It is something I do in lua to make the non shuffled ocarina captures work that interferes during the load process, hence you don't see it in the lttp pack.

**Comment by Hamsda** [comment]
I added a workaround in 992317bc1a4aae1bcec170cbadb47e9082f6223c. I'll close this for now, but am still hopeful to maybe get a callback once loading is done to "properly" fix it.
